package com.dariom.wds.api.common;

public enum ErrorCode {
  UNAUTHENTICATED,
  FORBIDDEN,
  ROOM_ACCESS_DENIED,
  USER_NOT_FOUND,
  ROOM_NOT_FOUND,
  ROOM_FULL,
  PLAYER_NOT_IN_ROOM,
  ROOM_NOT_IN_PROGRESS,
  ROOM_NOT_READY,
  PLAYER_DONE,
  NO_ATTEMPTS_LEFT,
  INVALID_LENGTH,
  INVALID_CHARS,
  INVALID_LANGUAGE,
  INVALID_ROUND_NUMBER,
  WORD_NOT_ALLOWED,
  INVALID_WORD,
  ROOM_CLOSED,
  ROOM_BUSY,
  DICTIONARY_EMPTY,
  GENERIC_BAD_REQUEST,

  UNKNOWN_ERROR,
}
