package com.dariom.wds.api.v1.error;

public enum ErrorCode {
  ROOM_NOT_FOUND,
  ROOM_FULL,
  PLAYER_NOT_IN_ROOM,
  ROOM_NOT_IN_PROGRESS,
  PLAYER_DONE,
  NO_ATTEMPTS_LEFT,
  INVALID_LENGTH,
  INVALID_CHARS,
  INVALID_LANGUAGE,
  WORD_NOT_ALLOWED,
  INVALID_WORD,
  INVALID_PLAYER_ID,
  ROOM_CLOSED,
  DICTIONARY_EMPTY,
  GENERIC_BAD_REQUEST,

  UNKNOWN_ERROR,
}
