name: Build and push image to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push_java:
    permissions:
      contents: read
    uses: dario-mr/ci-pipelines/.github/workflows/build-and-push-java.yml@main
    with:
      image-repo: dariomr8/wordle-duel-service
      with-redis: true
      with-postgres: true
      dockerfile: Dockerfile.native
      platforms: linux/amd64
      runner-label: ubuntu-24.04
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
